import { FC, PropsWithChildren } from "react";
import type { Metadata } from "next";

import BodyBackground from "@/components/atoms/BodyBackground";
import ActiveSection from "@/components/molecules/ActiveSection";
import FloatingContact from "@/components/molecules/FloatingContact";
import Footer from "@/components/molecules/Footer";
import LanguageSwitch from "@/components/molecules/LanguageSwitch";

import { Language } from "@/@types/i18n";
import { proximaNova } from "@/assets/fonts";
import en from "@/messages/en.json";
import ptBr from "@/messages/pt-br.json";
import { I18nProvider } from "@/store/i18n";

import "@/assets/globals.scss";
import styles from "./layout.module.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  params: Promise<{
    language: string;
  }>;
};

const RootLayout: FC<PropsWithChildren<Props>> = async ({
  children,
  params,
}) => {
  const language = (await params).language as Language;
  const t = language === "en" ? en : ptBr;
  return (
    <html lang={language} className={proximaNova.variable}>
      <I18nProvider language={language} t={t}>
        <body>
          <FloatingContact />
          <LanguageSwitch />
          <BodyBackground />
          <ActiveSection />
          <main className={styles.content}>{children}</main>
          <Footer />
        </body>
      </I18nProvider>
    </html>
  );
};

export default RootLayout;
